#!/bin/sh
###########VRP Generic Installer .1 Beta################
# Copyright Shane R. Nay (shane@agendacomputing.com)
# License terms under the GPL
# There are deficiencies in this program.  Specifically
# dealing with "diff"s of already present files.  This
# will have to be worked on, but the core is all here.


if [ ! -f $1 ]; then
	echo "Config file must be specified"
	exit 1;
fi
source $1
VRP_PACKAGE=$2

VRP_CONSIST="home|VRP_HOME"
VRP_CONSIST="${VRP_CONSIST}:root|VRP_ROOT|${VRP_ROOT}"
VRP_CONSIST="${VRP_CONSIST}:bin|VRP_BIN|${VRP_BIN}"
VRP_CONSIST="${VRP_CONSIST}:usrbin|VRP_USR_BIN|${VRP_USR_BIN}"
VRP_CONSIST="${VRP_CONSIST}:usrlocalbin|VRP_USR_LOCAL_BIN|${VRP_USR_BIN}"
VRP_CONSIST="${VRP_CONSIST}:etc|VRP_ETC|${VRP_ETC}"
VRP_CONSIST="${VRP_CONSIST}:usretc|VRP_USR_ETC|${VRP_USR_ETC}"
VRP_CONSIST="${VRP_CONSIST}:usrlocaletc|VRP_USR_LOCAL_ETC|${VRP_USR_LOCAL_ETC}"
VRP_CONSIST="${VRP_CONSIST}:dev|VRP_DEV|${VRP_DEV}"
VRP_CONSIST="${VRP_CONSIST}:usrman|VRP_USR_MAN|${VRP_USR_MAN}"
VRP_CONSIST="${VRP_CONSIST}:usrlocalman|VRP_USR_LOCAL_MAN|${VRP_USR_LOCAL_MAN}"
VRP_CONSIST="${VRP_CONSIST}:lib|VRP_LIB|${VRP_LIB}"
VRP_CONSIST="${VRP_CONSIST}:usrlib|VRP_USR_LIB|${VRP_USR_LIB}"
VRP_CONSIST="${VRP_CONSIST}:usrlocallib|VRP_USR_LOCAL_LIB|${VRP_USR_LOCAL_LIB}"
VRP_CONSIST="${VRP_CONSIST}:share|VRP_SHARE|${VRP_SHARE}"
VRP_CONSIST="${VRP_CONSIST}:usrshare|VRP_USR_SHARE|${VRP_USR_SHARE}"
VRP_CONSIST="${VRP_CONSIST}:usrlocalshare|VRP_USR_LOCAL_SHARE|${VRP_USR_LOCAL_SHARE}"
VRP_CONSIST="${VRP_CONSIST}:doc|VRP_DOC|${VRP_DOC}"
VRP_CONSIST="${VRP_CONSIST}:usrdoc|VRP_USR_DOC|${VRP_USR_DOC}"
VRP_CONSIST="${VRP_CONSIST}:usrlocaldoc|VRP_USR_LOCAL_DOC|${VRP_USR_LOCAL_DOC}"
VRP_CONSIST="${VRP_CONSIST}:sbin|VRP_SBIN|${VRP_SBIN}"
VRP_CONSIST="${VRP_CONSIST}:usrsbin|VRP_USR_SBIN|${VRP_USR_SBIN}"
VRP_CONSIST="${VRP_CONSIST}:usrlocalsbin|VRP_USR_LOCAL_SBIN|${VRP_USR_LOCAL_SBIN}"
VRP_CONSIST="${VRP_CONSIST}:log|VRP_LOG|${VRP_LOG}"
VRP_CONSIST="${VRP_CONSIST}:usr|VRP_USR|${VRP_USR}"
VRP_CONSIST="${VRP_CONSIST}:usrlocal|VRP_USR_LOCAL|${VRP_USR_LOCAL}"

PACKAGEFILE=${VRP_PACKAGE##*/}
oIFS=$IFS
IFS=":";
for cnunsplit in $VRP_CONSIST; do
	TARNAME=${cnunsplit%%|*}
	[ ! -f ${VRP_TEMP}/${TARNAME}.tar.gz ] && continue
	PACKAGEPART=""
	PACKAGEPART=${cnunsplit#*|}
	LOGICALLOC=${PACKAGEPART%%|*}
	PACKAGEPART=${PACKAGEPART##*|}
	echo "|${LOGICALLOC}=" >> ${VRP_TEMP}/${PACKAGEFILE}.consist
	IFS=${oIFS#??}
	for filename in `/bin/zcat ${VRP_TEMP}/${TARNAME}.tar.gz|/bin/tar t` ; do
		echo "$filename" >> ${VRP_TEMP}/${PACKAGEFILE}.consist
	done
	cd ${VRP_OUTPUT}${PACKAGEPART}; /bin/zcat ${VRP_TEMP}/${TARNAME}.tar.gz|/bin/tar x
	/bin/rm -f ${VRP_TEMP}/${TARNAME}.tar.gz #Save space.
done
/bin/gzip ${VRP_TEMP}/${PACKAGEFILE}.consist
mv ${VRP_TEMP}/${PACKAGEFILE}.consist.gz $VRP_CONSIST_HOME


IFS=$oIFS
